AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  static-page-activity-tracker
  
  Sample SAM Template for static-page-activity-tracker

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  SaveActivityFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/save-activity
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /activity
            Method: GET
      Environment:
        Variables:
          ACTIVITY_TABLE: VALUE

Outputs:
  SaveActivityAPI:
    Description: "API Gateway endpoint URL for Save Activity Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/activity"
  SaveActivityFunction:
    Description: "Save Activity Lambda Function ARN"
    Value: !GetAtt SaveActivityFunction.Arn
  SaveActivityFunctionIamRole:
    Description: "Implicit IAM Role created for Save Activity function"
    Value: !GetAtt SaveActivityFunctionRole.Arn
