openapi: 3.0.3

info:
  title:
    Fn::Sub:
      '${Environment}-${AppName}-api-gateway-v2'
  description:
    Fn::Sub:
      'API Gateway v2 for ${Environment}-${AppName}'
  version: 0.0.1

#servers:
#  - url: 'https://3soiuq2mr0.execute-api.us-east-1.amazonaws.com'

paths:
  /activity:
    post:
      tags:
        - Activity
      description: 'Save activity'
      operationId: 'SaveActivity'
      security:
        - api_key: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivityDTO'
        required: true
      responses:
        201:
          description: 'Save activity confirmation'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        500:
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-request-validator: body-only
      x-amazon-apigateway-integration:
        type: 'AWS_PROXY'
        httpMethod: 'POST'
        passthroughBehavior: 'WHEN_NO_TEMPLATES'
        uri:
          Fn::Sub:
            - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SaveActivityFunctionArn}/invocations'
            - SaveActivityFunctionArn:
                Fn::Sub:
                  'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Environment}-${AppName}-save-activity-fn'
        payloadFormatVersion: 2.
      x-cors:
        allow-origins:
          - '*'
        allow-methods:
          - OPTIONS
          - POST
        allow-headers:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token

x-amazon-apigateway-request-validators:
  body-only:
    validateRequestBody: true
    validateRequestParameters: false

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header

  responses:
    BadRequest:
      description: 'Bad Request'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
    Unauthorized:
      description: 'Unauthorized'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
    Forbidden:
      description: 'Forbidden'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
    InternalServerError:
      description: 'Internal Server Error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'

  schemas:
    ActivityDTO:
      type: object
      additionalProperties: false
      required:
        - page
        - activityType
        - data
      properties:
        page:
          type: string
          minLength: 4
          maxLength: 2048
        activityType:
          type: string
          enum:
            - 'PAGE_LOADED'
            - 'LINK_CLICK'
            - 'CUSTOM_EVENT'
        data:
          type: object
          minProperties: 1

    ErrorDTO:
      type: object
      additionalProperties: false
      required:
        - 'statusCode'
        - 'errorMessage'
      properties:
        statusCode:
          type: string
        errorMessage:
          type: string
